export const galleryList = [
    { src: '/images/memories/first_yt.jpg', name: 'Recording my first YouTube video' },
    { src: '/images/memories/team_greenjam.jpg', name: 'My first Game Jam (Global Game Jam 2022 Latvia) | Team GreenJam' },
    { src: '/images/memories/first_song.jpg', name: 'First song cover | \'I\'ll Let Me Be Me\'' },
    { src: '/images/memories/first_cover.jpg', name: 'First logo cover art I made' },
    { src: '/images/memories/firstmeetup_1.jpg', name: 'GameDev Estonia | GameDev Meetup #1 2022' },
    { src: '/images/memories/firstmeetup_2.jpg', name: 'GameDev Estonia | GameDev Meetup #1 2022' },
    { src: '/images/memories/firstmeetup_3.jpg', name: 'GameDev Estonia | GameDev Meetup #1 2022' },
    { src: '/images/memories/summerconf22_1.jpg', name: 'Aegcon 2022 | GameDev Summer Conference' },
    { src: '/images/memories/summerconf22_2.jpg', name: 'Aegcon 2022 | GameDev Summer Conference' },
    { src: '/images/memories/christmas_1.jpg', name: 'GameDev Estonia | Christmas GameDev Meetup #5 2022' },
    { src: '/images/memories/christmas_2.jpg', name: 'GameDev Estonia | Christmas GameDev Meetup #5 2022' },
    { src: '/images/memories/christmas_3.jpg', name: 'GameDev Estonia | Christmas GameDev Meetup #5 2022' },
    { src: '/images/memories/mobidictum23.jpg', name: 'Mobidictum Tallinn 2023' },
    { src: '/images/memories/moo23.jpg', name: 'MängudeÖÖ 2023 | First MängudeÖÖ I\'ve been at' },
    { src: '/images/memories/indieshowcase23.jpg', name: 'Indie Showcase 2023' },
    { src: '/images/memories/AlacrisDevs.jpg', name: 'AlacrisDevs photoshoot' },
    { src: '/images/memories/photoshoot_1.jpg', name: 'AlacrisDevs photoshoot' },
    { src: '/images/memories/photoshoot_2.jpg', name: 'AlacrisDevs photoshoot' },
    { src: '/images/memories/gamecamp24_1.jpg', name: 'TalTech GameCamp 2024' },
    { src: '/images/memories/gamecamp24_2.jpg', name: 'TalTech GameCamp 2024' },
    { src: '/images/memories/gamecamp24_3.jpg', name: 'TalTech GameCamp 2024' },
    { src: '/images/memories/gamedevguild24first_1.jpg', name: 'Gamedev Guild #1 2024' },
    { src: '/images/memories/gamedevguild24first_2.jpg', name: 'Gamedev Guild #1 2024' },
    { src: '/images/memories/gamedevguild24first_3.jpg', name: 'Gamedev Guild #1 2024' },
    { src: '/images/memories/gamedevguild24second_1.jpg', name: 'Gamedev Guild #2 2024' },
    { src: '/images/memories/gamedevguild24second_2.jpg', name: 'Gamedev Guild #2 2024' },
    { src: '/images/memories/recording.jpg', name: 'TalTech GameCamp Lite video recording' },
    { src: '/images/memories/gamecamplite_1.jpg', name: 'TalTech GameCamp Lite' },
    { src: '/images/memories/gamecamplite_2.jpg', name: 'TalTech GameCamp Lite' },
    { src: '/images/memories/gamecamplite_3.jpg', name: 'TalTech GameCamp Lite' },
    { src: '/images/memories/telehommik_1.jpg', name: 'TalTech GameCamp Winners | Telehommik' },
    { src: '/images/memories/telehommik_2.jpg', name: 'TalTech GameCamp Winners | Telehommik' },
    { src: '/images/memories/telehommik_3.jpg', name: 'TalTech GameCamp Winners | Telehommik' },
    { src: '/images/memories/moo24_1.jpg', name: 'MängudeÖÖ 2024' },
    { src: '/images/memories/moo24_2.jpg', name: 'MängudeÖÖ 2024' },
    { src: '/images/memories/moo24_3.jpg', name: 'MängudeÖÖ 2024' },
];